version: '3.7'

services:
    # GLPI container
    glpi:
        build: $PWD/glpi/build/
        ports:
            - "8080:80"
        links:
            - db:db
        env_file:
            - ./glpi.env
        volumes:
            - glpi_data:/var/www/html/glpi

    # Database container
    db:
        image: mariadb
        env_file:
            - ./glpi.env
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
    glpi_data: {}
    mysql_data: {}
